import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialState,transition,validateConfig,defaults} from '../lib/engine.ts';
import {validateQuote,createLiveAdapter} from '../lib/live.ts';
const now=1000000,prices={BTC:80000,ETH:3000,SOL:150};
function run(s:any,a:any,key:string='command-0001',time=now,marks=prices){return transition(s,a,key,time,marks);}
test('opens a single cycle; duplicate request cannot double-spend',()=>{const first=run(initialState(now),{type:'tick'});assert.equal(first.error,undefined);assert.equal(first.state.positions.length,3);assert.equal(first.state.cycle,1);const duplicate=run(first.state,{type:'tick'});assert.equal(duplicate.duplicate,true);assert.deepEqual(duplicate.state,first.state);const again=run(first.state,{type:'tick'},'command-0002');assert.equal(again.state.cycle,1);assert.equal(again.state.positions.length,3);});
test('idempotency key cannot be reused for a different action',()=>{const a=run(initialState(now),{type:'tick'});assert.throws(()=>run(a.state,{type:'claim'}),/different command/);});
test('allocation totals and NaN are rejected',()=>{assert.throws(()=>validateConfig({...defaults,allocation:{BTC:33,ETH:33,SOL:33}}));assert.throws(()=>validateConfig({...defaults,leverage:NaN}));assert.throws(()=>validateConfig({...defaults,slippageBps:500}));});
test('notional cap and nonnegative integer balances hold across leverage range',()=>{for(let leverage=1;leverage<=100;leverage++){const s=initialState(now);s.config.leverage=leverage;const r=run(s,{type:'tick'});assert.equal(r.error,undefined,'leverage '+leverage);assert.ok(r.state.ready>=0);assert.ok(r.state.positions.every(p=>p.notional<=100000));assert.equal(r.state.positions.length,3);}});
test('pause blocks new opens/claim/buyback but permits protective closes',()=>{let s=run(initialState(now),{type:'tick'}).state;s=run(s,{type:'pause'},'command-0002').state;const declined=run(s,{type:'claim'},'command-0003');assert.match(declined.error!,/paused/);const stopped=run(s,{type:'tick'},'command-0004',now+1000,{BTC:70000,ETH:2600,SOL:130});assert.ok(stopped.state.positions.every(p=>p.status!=='open'));assert.equal(stopped.state.cycle,1);assert.equal(stopped.state.bought,0);});
test('buyback is funded only by positive net cycle PnL, not principal',()=>{let s=run(initialState(now),{type:'tick'}).state;const collateral=s.positions.reduce((a,p)=>a+p.collateral,0);const closed=run(s,{type:'close'},'command-0002',now+1000,{BTC:88000,ETH:3300,SOL:165});assert.equal(closed.error,undefined);s=closed.state;assert.ok(s.realized>0);assert.equal(s.profitReserve,Math.floor(s.cyclePnl*.75));assert.ok(s.profitReserve<collateral);const before=s.ready;s=run(s,{type:'buyback'},'command-0003',now+2000).state;assert.equal(s.ready,before);assert.equal(s.profitReserve,0);assert.ok(s.bought>0);});
test('cross-market losses offset gains before profit reservation',()=>{let s=run(initialState(now),{type:'tick'}).state;s=run(s,{type:'close'},'command-0002',now+1000,{BTC:84000,ETH:2850,SOL:142.5}).state;assert.ok(s.cyclePnl<0);assert.equal(s.profitReserve,0);assert.equal(s.bought,0);});
test('TP closes automatically and cooldown prevents immediate reopen',()=>{let s=run(initialState(now),{type:'tick'}).state;s=run(s,{type:'tick'},'command-0002',now+1000,{BTC:100000,ETH:3750,SOL:187.5}).state;assert.ok(s.positions.every(p=>p.status==='closed'));assert.ok(s.bought>0);assert.equal(s.cycle,1);assert.equal(s.nextCycleAt,now+1000+120000);});
test('invalid prices roll back economic effects and log failure',()=>{const s=initialState(now);const r=run(s,{type:'tick'},'command-0001',now,{BTC:NaN,ETH:3000,SOL:150});assert.ok(r.error);assert.equal(r.state.pending,s.pending);assert.equal(r.state.positions.length,0);assert.equal(r.state.events[0].status,'failed');});
test('liquidation cannot credit a negative balance',()=>{let s=run(initialState(now),{type:'tick'}).state;s=run(s,{type:'close'},'command-0002',now+1000,{BTC:1,ETH:1,SOL:1}).state;assert.ok(s.positions.every(p=>p.status==='liquidated'));assert.ok(s.ready>=0);assert.equal(s.profitReserve,0);});
test('manual closing twice cannot return collateral twice',()=>{let s=run(initialState(now),{type:'tick'}).state;s=run(s,{type:'close'},'command-0002').state;const r=run(s,{type:'close'},'command-0003');assert.match(r.error!,/No matching/);assert.equal(r.state.ready,s.ready);});
test('existing positions keep original leverage and TP after configuration',()=>{let s=run(initialState(now),{type:'tick'}).state;s=run(s,{type:'configure',config:{...defaults,leverage:20,takeProfit:50}},'command-0002').state;assert.ok(s.positions.every(p=>p.leverage===5&&p.tp===100));});
test('live adapter always fails closed; quote account tampering rejected',()=>{assert.throws(createLiveAdapter,/not implemented/);const intent={owner:'owner',mint:'out',destination:'treasury',amount:BigInt(10),maxSlippageBps:50,expiresAt:now+5000,allowedPrograms:['approved']};const quote={owner:'owner',inputMint:'in',outputMint:'out',destination:'treasury',inputAmount:BigInt(10),minOutputAmount:BigInt(9),slippageBps:50,expiresAt:now+1000,programs:['approved']};assert.equal(validateQuote(quote,intent,'in',now),true);assert.throws(()=>validateQuote({...quote,destination:'attacker'},intent,'in',now));assert.throws(()=>validateQuote({...quote,programs:['unknown']},intent,'in',now));});

