import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import {initialState} from '../lib/engine.ts';import {command,readVault} from '../lib/store.ts';
function database(){const sql=new DatabaseSync(':memory:');for(const m of ['0000_tek_vault','0001_durable_receipts'])sql.exec(readFileSync('drizzle/'+m+'.sql','utf8'));sql.prepare('INSERT INTO vaults (owner,version,state) VALUES (?,0,?)').run('alice',JSON.stringify({...initialState(),schemaVersion:2}));function prepare(query:string){let args:any[]=[];return {bind(...v:any[]){args=v;return this;},async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){return this.sync();},sync(){return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}};}}}return {sql,db:{prepare,async batch(stmts:any[]){sql.exec('BEGIN IMMEDIATE');try{const rows=stmts.map(s=>s.sync());sql.exec('COMMIT');return rows;}catch(e){sql.exec('ROLLBACK');throw e;}}} as unknown as D1Database};}
test('20 competing duplicate commands commit one cycle and one receipt',async()=>{const {sql,db}=database();const results=await Promise.all(Array.from({length:20},()=>command('alice',{type:'tick'},'same-command-001',db)));assert.ok(results.every(r=>!r.error));const row=await readVault('alice',db);const s=JSON.parse(row.state);assert.equal(s.cycle,1);assert.equal(s.positions.length,3);assert.equal(sql.prepare('SELECT count(*) as n FROM commands').get()!.n,1);assert.equal(sql.prepare('SELECT count(*) as n FROM activity').get()!.n,4);sql.close();});
test('competing distinct keeper runs cannot double-open',async()=>{const {sql,db}=database();await Promise.all(Array.from({length:4},(_,i)=>command('alice',{type:'tick'},'distinct-command-'+i,db)));const s=JSON.parse((await readVault('alice',db)).state);assert.equal(s.cycle,1);assert.equal(s.positions.length,3);assert.equal(sql.prepare('SELECT count(*) as n FROM commands').get()!.n,4);sql.close();});
test('receipts survive reloading and reject command substitution',async()=>{const {sql,db}=database();await command('alice',{type:'tick'},'command-reload-01',db);assert.equal((await command('alice',{type:'tick'},'command-reload-01',db)).duplicate,true);await assert.rejects(command('alice',{type:'close'},'command-reload-01',db),/different command/);sql.close();});
test('vault ownership isolates balances and pause state',async()=>{const {sql,db}=database();await command('alice',{type:'pause'},'alice-command-01',db);const bob=JSON.parse((await readVault('bob',db)).state);assert.equal(bob.paused,true);assert.equal(bob.ready,0);assert.equal(bob.cycle,0);sql.close();});

test('legacy demo data is retired without changing public addresses or strategy',async()=>{
 const {sql,db}=database();const state=initialState();state.config.tokenMint='EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';state.config.leverage=7;
 sql.prepare('UPDATE vaults SET state=? WHERE owner=?').run(JSON.stringify(state),'alice');
 sql.prepare('INSERT INTO activity (owner,id,time,event) VALUES (?,?,?,?)').run('alice','fake-receipt',Date.now(),'{}');
 const next=JSON.parse((await readVault('alice',db)).state);
 assert.equal(next.config.tokenMint,state.config.tokenMint);assert.equal(next.config.leverage,7);assert.equal(next.config.dataSource,'mainnet');assert.equal(next.pending,0);assert.equal(next.ready,0);assert.equal(next.bought,0);assert.deepEqual(next.positions,[]);assert.deepEqual(next.events,[]);assert.equal(sql.prepare('SELECT count(*) AS n FROM activity').get()!.n,0);
 assert.equal((await command('alice',{type:'tick'},'live-only-test',db)).error?.includes('read-only'),true);sql.close();
});
