"use client";
import {useEffect,useState} from 'react';
type Entry={id:number;time:number;level:string;source:string;message:string};
export function AdminConsole({enabled}:{enabled:boolean}){
 const [entries,setEntries]=useState<Entry[]>([]),[error,setError]=useState(''),[watch,setWatch]=useState(true),[query,setQuery]=useState(''),[level,setLevel]=useState('all');
 const filtered=entries.filter(e=>(level==='all'||e.level===level)&&`${e.source} ${e.message}`.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{if(!enabled||!watch)return;let cancelled=false;async function refresh(){try{const r=await fetch('/api/logs',{cache:'no-store'});if(!r.ok)throw Error('Console unavailable. Sign in again.');const value=await r.json() as {entries:Entry[]};if(!cancelled){setEntries(value.entries);setError('');}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Console unavailable.');}}void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>{cancelled=true;clearInterval(timer);};},[enabled,watch]);
 return <details open className="panel settings-section admin-tab-panel"><summary>Console <small> · {watch?'Live':'Paused'}</small></summary><p>Application diagnostics · updates every 5 seconds · credentials hidden. Hosting build logs remain in Railway.</p><div className="console-toolbar"><input aria-label="Search logs" placeholder="Search events…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter log level" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">All events</option><option value="error">Errors</option><option value="warn">Warnings</option><option value="info">Info</option></select><button type="button" className="secondary" onClick={()=>setWatch(!watch)}>{watch?'Pause updates':'Resume updates'}</button></div>{error&&<p role="alert" className="negative">{error}</p>}<div role="log" aria-label="Application console" aria-live="off" className="console-stream">{filtered.length?filtered.map(e=><div key={e.id} className="console-entry"><time>{new Date(e.time).toLocaleString()}</time><span className={'log-level log-'+e.level}>{e.level}</span><div><span className="log-source">{e.source}</span><p>{e.message}</p></div></div>):<p className="console-empty">{!enabled?'Console is available on the deployed Admin page.':entries.length?'No events match your filters.':'No events yet.'}</p>}</div></details>;
}
