// @ts-nocheck -- Three.js scene is isolated from the typed financial dashboard.
import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
const bgVertex="void main() { gl_Position = vec4(position.xy, 0.999, 1.0); }\n";
const bgFragment="uniform vec2 uResolution;\nuniform vec2 uCenter;\nuniform vec2 uSpread;\nuniform vec3 uColorInner;\nuniform vec3 uColorMid;\nuniform vec3 uColorOuter;\nuniform float uStopMid;\nuniform float uDither;\nuniform float uTime;\n\nfloat hash21(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }\n\nvoid main() {\n  vec2 uv = gl_FragCoord.xy / uResolution;\n  vec2 p = (uv - uCenter) / uSpread;\n  float r = length(p);\n  vec3 c = mix(uColorInner, uColorMid, smoothstep(0.0, uStopMid, r));\n  c = mix(c, uColorOuter, smoothstep(uStopMid, 1.0, r));\n  // Screen-space grain breaks 8-bit banding.\n  float n = hash21(floor(gl_FragCoord.xy)) - 0.5;\n  c += n * uDither;\n  gl_FragColor = vec4(c, 1.0);\n}\n";
const simplex="vec3 permute(vec3 x) { return mod(((x * 34.0) + 1.0) * x, 289.0); }\nfloat snoise(vec2 v) {\n  const vec4 C = vec4(0.211324865405187, 0.366025403784439, -0.577350269189626, 0.024390243902439);\n  vec2 i = floor(v + dot(v, C.yy));\n  vec2 x0 = v - i + dot(i, C.xx);\n  vec2 i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);\n  vec4 x12 = x0.xyxy + C.xxzz; x12.xy -= i1;\n  i = mod(i, 289.0);\n  vec3 p = permute(permute(i.y + vec3(0.0, i1.y, 1.0)) + i.x + vec3(0.0, i1.x, 1.0));\n  vec3 m = max(0.5 - vec3(dot(x0, x0), dot(x12.xy, x12.xy), dot(x12.zw, x12.zw)), 0.0);\n  m = m * m; m = m * m;\n  vec3 x = 2.0 * fract(p * C.www) - 1.0;\n  vec3 h = abs(x) - 0.5;\n  vec3 ox = floor(x + 0.5);\n  vec3 a0 = x - ox;\n  m *= 1.79284291400159 - 0.85373472095314 * (a0 * a0 + h * h);\n  vec3 g; g.x = a0.x * x0.x + h.x * x0.y; g.yz = a0.yz * x12.xz + h.yz * x12.yw;\n  return 130.0 * dot(m, g);\n}\n";
const dotVertex="uniform float uTime, uProgress, uSpacing, uDotSize, uNoiseScale, uNoiseSpeed, uOpacity;\nuniform float uOuterR, uInnerR, uInnerFade;\nuniform vec2 uCursor, uCursorLag;\nuniform float uLiftRadius, uLiftFalloff, uLiftStrength, uLiftStagger, uViewportH;\nattribute float aHash;\nvarying float vAlpha;\n// \u2026 SIMPLEX chunk here \u2026\nvoid main() {\n  vec2 p = position.xy;\n  vec2 id = floor(p * uSpacing);\n  float n = snoise(id * uNoiseScale + vec2(uTime * uNoiseSpeed, uTime * uNoiseSpeed * 0.63));\n  float vis = smoothstep(-0.55, 0.75, n);\n  float rad = length(p);\n  float field = 1.0 - smoothstep(uOuterR - 0.05, uOuterR, rad);\n  float tIn = smoothstep(uInnerR, uInnerR + max(uInnerFade, 1e-3), rad);\n  field *= tIn * tIn;\n  float radialShade = mix(0.55, 1.0, smoothstep(0.0, uOuterR, rad));\n  vAlpha = field * radialShade * (0.15 + 0.85 * vis) * uOpacity * uProgress;\n  vec2 cur = mix(uCursor, uCursorLag, uLiftStagger * aHash);\n  float dc = distance(p, cur);\n  float t = 1.0 - smoothstep(uLiftRadius, uLiftRadius + max(uLiftFalloff, 1e-3), dc);\n  float lift = uLiftStrength * t * t * uProgress;\n  vec4 mv = modelViewMatrix * vec4(p, lift, 1.0);\n  gl_Position = projectionMatrix * mv;\n  float scale = length(modelViewMatrix[0].xyz);\n  float worldDia = (uDotSize / uSpacing) * scale;\n  gl_PointSize = worldDia * projectionMatrix[1][1] * uViewportH * 0.5 / max(-mv.z, 1e-4);\n}\n";
const dotFragment="uniform vec3 uColor;\nvarying float vAlpha;\nvoid main() {\n  float d = length(gl_PointCoord - 0.5);\n  float aa = max(fwidth(d), 0.06);\n  float alpha = (1.0 - smoothstep(0.5 - aa, 0.5, d)) * vAlpha;\n  if (alpha < 0.003) discard;\n  gl_FragColor = vec4(uColor, alpha);\n}\n";
const holoVertex="#include <common>\nattribute vec3 aBary;\nvarying vec3 vBary, vNorm, vView, vObj;\nvoid main() {\n  vBary = aBary; vObj = position;\n  vec4 mv = modelViewMatrix * vec4(position, 1.0);\n  vNorm = normalize(normalMatrix * normal);\n  vView = normalize(-mv.xyz);\n  gl_Position = projectionMatrix * mv;\n}\n";
const holoFragment="uniform vec3 uColor, uAccent, uUpAxis;\nuniform float uPulse, uOpacity, uFill, uFresnel;\nuniform float uScanDensity, uScanSpeed, uTime, uReveal;\nuniform float uYMin, uYMax, uWire;\nvarying vec3 vBary, vNorm, vView, vObj;\nfloat edgeFactor() {\n  vec3 d = fwidth(vBary);\n  vec3 a3 = smoothstep(vec3(0.0), d * 1.4, vBary);\n  return 1.0 - min(min(a3.x, a3.y), a3.z);\n}\nvoid main() {\n  float ndv = abs(dot(normalize(vNorm), normalize(vView)));\n  float fres = pow(max(1.0 - ndv, 0.0), uFresnel);\n  float yn = (dot(vObj, uUpAxis) - uYMin) / max(uYMax - uYMin, 1e-4);\n  float scan = 0.5 + 0.5 * sin((yn * uScanDensity - uTime * uScanSpeed) * 6.2831853);\n  scan = mix(0.55, 1.0, scan);\n  float revealY = mix(-0.06, 1.06, uReveal);\n  float vis = 1.0 - smoothstep(revealY - 0.02, revealY + 0.02, yn);\n  float line = exp(-abs(yn - revealY) * 55.0) * smoothstep(1.0, 0.94, uReveal);\n  float wire = edgeFactor() * uWire;\n  float body = (uFill + fres) * scan;\n  float a = (body + wire) * vis * uOpacity * (1.0 + uPulse * 0.6);\n  a += line * uOpacity * 0.9;\n  if (a < 0.002) discard;\n  vec3 base = mix(uColor, uAccent, uPulse);\n  vec3 c = base * (0.5 + 1.0 * fres) + base * wire * 1.15 + vec3(line * 0.8);\n  gl_FragColor = vec4(c, a);\n}\n";
export function mountCandle(host,ready){
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.NoToneMapping;
 host.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,0,6);
 scene.add(new THREE.AmbientLight(0xffffff,1.1));const light=new THREE.DirectionalLight(0xffffff,2.2);light.position.set(2,3,4);scene.add(light);
 const u=value=>({value}),color=h=>new THREE.Color(h);
 const bgGeo=new THREE.BufferGeometry();bgGeo.setAttribute('position',new THREE.Float32BufferAttribute([-1,-1,0,1,-1,0,-1,1,0,1,-1,0,1,1,0,-1,1,0],3));
 const bgMat=new THREE.ShaderMaterial({vertexShader:bgVertex,fragmentShader:bgFragment,depthTest:false,depthWrite:false,uniforms:{uResolution:u(new THREE.Vector2()),uCenter:u(new THREE.Vector2(.5,.7)),uSpread:u(new THREE.Vector2(.62,.52)),uColorInner:u(color('#070d0b')),uColorMid:u(color('#070d0b')),uColorOuter:u(color('#040806')),uStopMid:u(.55),uDither:u(.018),uTime:u(0)}});
 const bg=new THREE.Mesh(bgGeo,bgMat);bg.frustumCulled=false;bg.renderOrder=-10;scene.add(bg);
 const pos=[],hash=[],spacing=25.5,a=Math.ceil(2.6*spacing);
 for(let n=-a;n<a;n++)for(let i=-a;i<a;i++){const x=(n+.5)/spacing,y=(i+.5)/spacing;if(x*x+y*y>2.6*2.6)continue;pos.push(x,y,0);const h=43758.5453*Math.sin(127.1*n+311.7*i);hash.push(h-Math.floor(h));}
 const dotGeo=new THREE.BufferGeometry();dotGeo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));dotGeo.setAttribute('aHash',new THREE.Float32BufferAttribute(hash,1));
 const dotMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,vertexShader:simplex+dotVertex,fragmentShader:dotFragment,uniforms:{uTime:u(0),uProgress:u(0),uSpacing:u(spacing),uDotSize:u(.38),uNoiseScale:u(.02),uNoiseSpeed:u(.3),uOpacity:u(1),uOuterR:u(2.45),uInnerR:u(0),uInnerFade:u(.2),uCursor:u(new THREE.Vector2()),uCursorLag:u(new THREE.Vector2()),uLiftRadius:u(.52),uLiftFalloff:u(1.5),uLiftStrength:u(-1.5),uLiftStagger:u(1),uViewportH:u(1),uColor:u(color('#3d6a5c'))}});
 const dots=new THREE.Points(dotGeo,dotMat);dots.position.z=-2;dots.frustumCulled=false;scene.add(dots);
 const pieces=[new THREE.BoxGeometry(.82,1.65,.64,5,12,4),new THREE.BoxGeometry(.065,.68,.065,1,5,1).translate(0,1.165,0),new THREE.BoxGeometry(.065,.52,.065,1,4,1).translate(0,-1.085,0)];
 const merged=mergeGeometries(pieces),geo=merged.toNonIndexed();merged.dispose();pieces.forEach(p=>p.dispose());const bary=new Float32Array(geo.attributes.position.count*3);for(let i=0;i<geo.attributes.position.count;i+=3){bary[i*3]=1;bary[(i+1)*3+1]=1;bary[(i+2)*3+2]=1;}geo.setAttribute('aBary',new THREE.BufferAttribute(bary,3));
 const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,vertexShader:holoVertex,fragmentShader:holoFragment,uniforms:{uColor:u(color('#2dd409')),uAccent:u(color('#f2d24b')),uUpAxis:u(new THREE.Vector3(0,1,0)),uPulse:u(0),uOpacity:u(.5),uFill:u(.02),uFresnel:u(2.3),uScanDensity:u(26),uScanSpeed:u(1.1),uTime:u(0),uReveal:u(0),uYMin:u(-1.345),uYMax:u(1.505),uWire:u(.16)}});
 const root=new THREE.Group(),scale=new THREE.Group(),spin=new THREE.Group(),bob=new THREE.Group();root.add(scale);scale.add(spin);spin.add(bob);scene.add(root);root.position.y=.05;scale.scale.setScalar(.98);bob.add(new THREE.Mesh(geo,mat));
 const target=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,samples:4}),composer=new EffectComposer(renderer,target),render=new RenderPass(scene,camera),bloom=new UnrealBloomPass(new THREE.Vector2(1,1),.22,.4,0),output=new OutputPass();composer.addPass(render);composer.addPass(bloom);composer.addPass(output);
 const ray=new THREE.Raycaster(),ndc=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,0,1),2),hit=new THREE.Vector3(),cursor=new THREE.Vector2(),lag=new THREE.Vector2();
 const motion=matchMedia('(prefers-reduced-motion: reduce)');let stopped=false,visible=true,frame=0,last=0,t=0,progress=0;
 function pointer(e){if(motion.matches)return;const r=host.getBoundingClientRect();ndc.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(ndc,camera);if(ray.ray.intersectPlane(plane,hit))cursor.set(hit.x,hit.y);}
 function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);composer.setSize(w,h);draw(0);}
 function draw(dt){t+=dt;progress=motion.matches?1:THREE.MathUtils.damp(progress,1,2.4,dt);lag.x=THREE.MathUtils.damp(lag.x,cursor.x,6,dt);lag.y=THREE.MathUtils.damp(lag.y,cursor.y,6,dt);bgMat.uniforms.uResolution.value.set(renderer.domElement.width,renderer.domElement.height);dotMat.uniforms.uTime.value=t;dotMat.uniforms.uProgress.value=progress;dotMat.uniforms.uViewportH.value=renderer.domElement.height;dotMat.uniforms.uCursor.value.copy(cursor);dotMat.uniforms.uCursorLag.value.copy(lag);spin.rotation.y=motion.matches?.45:spin.rotation.y+dt*(1.94+(1-progress)*4);bob.position.y=.02+(motion.matches?0:.015*Math.sin(1.1*t));const s=THREE.MathUtils.clamp(progress,0,1),ease=1+2.70158*Math.pow(s-1,3)+1.70158*Math.pow(s-1,2);bob.scale.setScalar(.6+.4*ease);mat.uniforms.uTime.value=t;mat.uniforms.uReveal.value=progress;mat.uniforms.uOpacity.value=progress*.5;composer.render();}
 function tick(now){frame=0;if(stopped||!visible||document.hidden)return;draw(Math.min((now-(last||now))/1000,.05));last=now;if(!motion.matches)frame=requestAnimationFrame(tick);}
 function wake(){cancelAnimationFrame(frame);last=0;if(!stopped&&visible&&!document.hidden)frame=requestAnimationFrame(tick);}
 const observer=new ResizeObserver(resize),intersection=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;wake();});observer.observe(host);intersection.observe(host);host.addEventListener('pointermove',pointer);document.addEventListener('visibilitychange',wake);motion.addEventListener('change',wake);
 const lost=e=>{e.preventDefault();stopped=true;cancelAnimationFrame(frame);host.dataset.fallback='true';};renderer.domElement.addEventListener('webglcontextlost',lost);resize();wake();ready();
 return()=>{stopped=true;cancelAnimationFrame(frame);observer.disconnect();intersection.disconnect();host.removeEventListener('pointermove',pointer);document.removeEventListener('visibilitychange',wake);motion.removeEventListener('change',wake);renderer.domElement.removeEventListener('webglcontextlost',lost);[bgGeo,dotGeo,geo,bgMat,dotMat,mat].forEach(x=>x.dispose());bloom.dispose();output.dispose();composer.dispose();renderer.dispose();renderer.domElement.remove();};
}
