"use client";
import {useEffect,useState,useCallback,useRef} from 'react';
import {Activity,Settings2,Zap,Play,Pause,Copy,ArrowDownToLine,RotateCcw,ShieldCheck,RefreshCw,LogIn} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {defaults,MARKETS,type Config,type State,type Action} from '@/lib/engine';
type View=Omit<State,'processed'>&{owner:string;mode:'mock';keeperConfigured:boolean};
const usd=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(c/100);
const price=(n:number)=>usd(n*100);
const short=(s:string)=>s?s.slice(0,5)+'…'+s.slice(-5):'Not configured';
const fields:[keyof Config,string,string][]=[['leverage','Leverage (×)','1–100×; default 5×'],['minRewardUsd','Minimum cycle capital ($)','Minimum to claim automatically and open'],['takeProfit','Take profit (% ROE)','100% = 2× collateral before costs'],['stopLoss','Stop loss (% ROE)','Positive loss threshold; 1–90%'],['maxPositionUsd','Max position notional ($)','Per market; excess capital stays in vault'],['slippageBps','Slippage (basis points)','100 bps = 1%; live adapter policy only'],['cooldownSeconds','Cycle cooldown (seconds)','After the last position closes'],['buybackPercent','Profit to buyback (%)','Share of positive net cycle profit']];
export default function Home(){
 const [tab,setTab]=useState('overview'),[data,setData]=useState<View|null>(null),[draft,setDraft]=useState<Config>(structuredClone(defaults)),[error,setError]=useState(''),[auth,setAuth]=useState(false),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),[filter,setFilter]=useState('All'),[confirm,setConfirm]=useState<Action|null>(null),[failed,setFailed]=useState<{action:Action;key:string}|null>(null);
 const initialized=useRef(false);
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/vault',{cache:'no-store'});const d=await r.json() as View & {error?:string};if(!r.ok){setAuth(r.status===401);throw Error(d.error||'Could not load vault.');}setData(d);setAuth(false);setError('');if(!initialized.current){setDraft(d.config);initialized.current=true;}}catch(e){setError(e instanceof Error?e.message:'Vault unavailable.');}},[]);
 useEffect(()=>{void refresh();const t=setInterval(()=>void refresh(),5000);const clock=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(t);clearInterval(clock);};},[refresh]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const lifecycle=new AbortController();void Promise.resolve(ctx.registerTool({name:'read_vault',title:'Read vault status',description:'Read the authenticated simulated vault balances and positions. Does not trade.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments accepted');const r=await fetch('/api/vault');if(!r.ok)throw Error('Vault unavailable or sign-in required');const d=await r.json() as View & {error?:string};setData(d);return {mode:d.mode,paused:d.paused,ready:d.ready,positions:d.positions,lastTick:d.lastTick};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 async function act(action:Action,key=crypto.randomUUID()){if(busy)return;setBusy(true);setFailed(null);try{const r=await fetch('/api/vault',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(action)});const d=await r.json() as View & {error?:string};if(d.config)setData(d);if(!r.ok){if(r.status>=500)setFailed({action,key});throw Error(d.error||'Command failed.');}toast.success(action.type==='configure'?'Configuration saved':action.type==='tick'?'Simulation cycle evaluated':'Command confirmed');}catch(e){if(e instanceof TypeError)setFailed({action,key});toast.error(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);setConfirm(null);}}
 const c=data?.config||defaults,positions=data?.positions||[],open=positions.filter(p=>p.status==='open'),pnl=open.reduce((s,p)=>s+p.pnl,0),notional=open.reduce((s,p)=>s+p.notional,0),seconds=Math.max(0,Math.ceil(((data?.nextCycleAt||now)-now)/1000)),stale=!!data&&now-data.lastTick>45000;
 const events=(data?.events||[]).filter(e=>filter==='All'||e.kind===filter||(filter==='Failure'&&e.status==='failed'));
 async function copy(value:string){try{await navigator.clipboard.writeText(value);toast.success('Copied');}catch{toast.error('Could not copy. Select the address in Configuration.');}}
 return <><header className="topbar"><a className="brand" href="/"><b>↗</b> TEK <span>/ VAULT</span></a><span className="network">● Solana · Simulation</span></header><main><div className="hero"><div><div className="eyebrow">AUTOMATED CREATOR VAULT</div><h1>$TEK <span className="pill">MOCK MODE</span></h1><p>Creator rewards. Calculated exposure. Token buybacks.</p><div className="address">VAULT <span>{short(c.vault)}</span>{c.vault&&<button aria-label="Copy vault address" onClick={()=>copy(c.vault)}><Copy size={13}/></button>}</div></div><div className="stamp"><Zap size={36}/><span>REWARDS → LONGS → BUYBACKS</span></div></div>
 {error&&<div role="alert" className="error-box">{error} {auth?<a className="sign-in" href="/signin-with-chatgpt?return_to=/" target="_top"><LogIn size={15}/> Sign in with ChatGPT</a>:<button className="secondary" onClick={()=>refresh()}>Retry connection</button>}</div>}
 {failed&&<div className="error-box">The command was not confirmed. <button className="secondary" disabled={busy} onClick={()=>act(failed.action,failed.key)}>Retry same command</button></div>}
 <Tabs value={tab} onValueChange={setTab}><div className="nav"><TabsList><TabsTrigger value="overview"><Activity size={16}/> Overview</TabsTrigger><TabsTrigger value="admin"><Settings2 size={16}/> Configuration</TabsTrigger></TabsList><span>Isolated simulation · No real funds</span></div>
 <TabsContent value="overview"><div className="stats"><section className="panel"><label>Next cycle</label><strong className="positive">{!data?'—':data.paused?'Paused':data.cycleActive?'In position':seconds?String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0'):'Ready'}</strong><small>{stale?'Keeper idle · run a simulation cycle':data?.cycleActive?'Monitoring take profit and stop loss':'Runs when keeper evaluates the vault'}</small></section><section className="panel"><label>Open notional</label><strong>{usd(notional)}</strong><small className={pnl<0?'negative':'positive'}>{pnl>=0?'+':''}{usd(pnl)} unrealized PnL</small></section><section className="panel"><label>$TEK contract address</label><strong style={{fontSize:25}}>{short(c.tokenMint)}</strong>{c.tokenMint?<button className="text-button" onClick={()=>copy(c.tokenMint)}>Copy contract <Copy size={12}/></button>:<small>Set your token in Configuration</small>}</section></div>
 <div className="section-title"><h2>Capital pipeline</h2><span>Claim → Deploy → Realize → Buy back</span></div><div className="pipeline">{[['Pending creator rewards',data?.pending||0,'Simulated claimable value'],['Ready to deploy',data?.ready||0,'Available mock collateral'],['Realized PnL',data?.realized||0,'Net of simulated open / close fees'],['Token buybacks',data?.bought||0,'Cumulative simulated spend']].map(([label,value,sub])=><section key={label}><label>{label}</label><strong>{usd(Number(value))}</strong><small>{sub}</small></section>)}</div>
 <div className="section-title"><h2>Long positions <small>{open.length} ACTIVE / 3 MARKETS</small></h2><span>TP +{c.takeProfit}% ROE · SL −{c.stopLoss}% · {c.leverage}× next cycle</span></div>
 <div className="positions">{MARKETS.map((m,i)=>{const p=positions.find(x=>x.market===m),active=p?.status==='open',value=p?.pnl||0,roe=p?.roe||0,progress=p?Math.min(100,Math.max(0,roe/p.tp*100)):0,history=p?.history||[],min=Math.min(...history),max=Math.max(...history),distance=p?(p.mark-p.liquidation)/p.mark*100:0;const points=history.map((v,j)=>j/(history.length-1||1)*300+','+(60-(v-min)/(max-min||1)*48)).join(' ');return <article className="position" key={m}><div className="position-head"><span className={'coin coin-'+m}>{['₿','Ξ','≋'][i]}</span><div><h3>{m}</h3><span>{['Bitcoin','Ethereum','Solana'][i]}</span></div><b className="badge">{p?.leverage||c.leverage}× LONG</b></div><div className={'pnl '+(value<0?'negative':value>0?'positive':'')}>{value>0?'+':''}{usd(value)}</div><div className={'gain '+(roe<0?'negative':'')}>{roe>0?'+':''}{roe.toFixed(2)}% ROE <span>· {active?'Unrealized':p?'Realized':'Awaiting cycle'}</span></div>{history.length>1?<svg className="chart" viewBox="0 0 300 76" preserveAspectRatio="none" role="img" aria-label={m+' simulated mark price history'}><path d="M0 70H300" stroke="#293528"/><polyline points={points} fill="none" stroke={value<0?'#ff8d78':'#a5fa4c'} strokeWidth="2"/></svg>:<div className="chart-empty">{active?'Collecting simulated marks':'No position history yet'}</div>}<dl><div><dt>Collateral</dt><dd>{usd(p?.collateral||0)}</dd></div><div><dt>Mark price</dt><dd>{p?price(p.mark):'—'}</dd></div><div><dt>Notional</dt><dd>{usd(p?.notional||0)}</dd></div><div><dt>Est. liquidation</dt><dd className={active&&distance<5?'negative':''}>{p?price(p.liquidation):'—'}</dd></div></dl><div className="progress-label"><span>Progress to TP {p?'+'+p.tp+'%':''}</span><span>{progress.toFixed(0)}%</span></div><Progress value={progress} aria-label={m+' progress toward take profit'}/><footer><span>● {active?'Open · '+distance.toFixed(1)+'% to est. liquidation':p?.status==='liquidated'?'Liquidated':p?'Closed':'Waiting for capital'}</span>{active&&<button className="text-button" disabled={busy} onClick={()=>setConfirm({type:'close',market:m})}>Close ↗</button>}</footer></article>})}</div>
 <div className="risk"><ShieldCheck size={18}/><span>Leverage can liquidate all collateral. Mock liquidation estimates exclude funding, fees and oracle effects. Stop losses do not guarantee an exit.</span></div>
 <div className="section-title"><h2>Vault controls</h2><span>{data?.paused?'Paused · protective closes remain enabled':'Manual actions use the same keeper rules'}</span></div><div className="actions"><button className="primary" disabled={!data||busy} onClick={()=>act({type:'tick'})}><Play size={14}/> {busy?'Processing…':'Run simulation cycle'}</button><button className="secondary" disabled={!data||busy} onClick={()=>act({type:data?.paused?'resume':'pause'})}>{data?.paused?<Play size={14}/>:<Pause size={14}/>} {data?.paused?'Resume':'Emergency pause'}</button><button className="secondary" disabled={!data||busy||data.paused||!data.pending} onClick={()=>act({type:'claim'})}><ArrowDownToLine size={14}/> Claim rewards</button><button className="secondary" disabled={!data||busy||data.paused||!data.profitReserve} onClick={()=>act({type:'buyback'})}><RotateCcw size={14}/> Buy back {usd(data?.profitReserve||0)}</button><button className="secondary danger" disabled={!open.length||busy} onClick={()=>setConfirm({type:'close'})}>Close all positions</button></div>
 <div className="section-title"><h2>Transaction activity</h2><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Filter transaction activity"><SelectValue/></SelectTrigger><SelectContent>{['All','Claim','Open','Close','Buyback','Liquidation','Failure','Config','Cycle','Pause','Resume'].map(x=><SelectItem key={x} value={x}>{x==='All'?'All activity':x}</SelectItem>)}</SelectContent></Select></div>
 <div className="history"><Table><TableHeader><TableRow><TableHead>Action / details</TableHead><TableHead>Value</TableHead><TableHead>Status</TableHead><TableHead>Time</TableHead><TableHead>Receipt</TableHead></TableRow></TableHeader><TableBody>{events.map(e=><TableRow key={e.id}><TableCell><b>{e.kind}</b><div className="event-detail">{e.detail}</div></TableCell><TableCell className={e.amount<0?'negative':''}>{e.amount?usd(e.amount):'—'}</TableCell><TableCell><span className={e.status==='failed'?'negative':'positive'}>{e.status==='failed'?'Failed':'Simulated'}</span></TableCell><TableCell>{new Date(e.time).toLocaleTimeString()}</TableCell><TableCell>{e.signature?<button title={e.signature} className="text-button" onClick={()=>copy(e.signature!)}>mock:{e.signature.slice(-6)} <Copy size={12}/></button>:'—'}</TableCell></TableRow>)}</TableBody></Table>{!events.length&&<div className="empty">No activity yet. Run a simulation cycle to claim mock rewards and open positions.</div>}</div><p className="admin-note">Showing up to 200 recent events. Mock receipts are not blockchain signatures.</p>
 </TabsContent>
 <TabsContent value="admin"><form onSubmit={e=>{e.preventDefault();void act({type:'configure',config:draft});}}><section className="panel settings-section"><h2>Strategy & risk limits</h2><p>Applied to new positions. Existing positions retain their opening risk settings.</p><div className="field-grid">{fields.map(([key,label,hint])=><label key={key}>{label}<input required type="number" step="any" value={draft[key] as number} onChange={e=>setDraft({...draft,[key]:e.target.value===''?NaN:Number(e.target.value)})}/><small>{hint}</small></label>)}</div><h2>Capital allocation <small>Total {MARKETS.reduce((n,m)=>n+draft.allocation[m],0)}%</small></h2><div className="field-grid">{MARKETS.map(m=><label key={m}>{m} allocation (%)<input required type="number" min="0" max="100" step="0.1" value={draft.allocation[m]} onChange={e=>setDraft({...draft,allocation:{...draft.allocation,[m]:Number(e.target.value)}})}/></label>)}</div></section><section className="panel settings-section"><h2>Vault & treasury</h2><div className="field-grid">{([['vault','Vault address'],['treasury','Treasury address'],['tokenMint','$TEK token contract']] as const).map(([key,label])=><label key={key}>{label}<input autoComplete="off" spellCheck={false} value={draft[key]} placeholder="Solana public address" onChange={e=>setDraft({...draft,[key]:e.target.value.trim()})}/></label>)}</div><p className="admin-note">Public addresses only. Mock mode permits empty addresses. This app does not create a token or deploy an on-chain vault.</p></section><section className="panel settings-section"><h2>Connections & keeper</h2><div className="field-grid"><label>Execution mode<input readOnly value="Mock · Live adapter disabled"/></label><label>RPC secret reference<input readOnly value={draft.rpcEnv}/><small>Configure the server variable; never paste keys here.</small></label><label>Jupiter API secret reference<input readOnly value={draft.jupiterEnv}/><small>Reserved for a reviewed live integration.</small></label></div><p className="admin-note">Keeper owner ID: <code>{data?.owner||'Sign in first'}</code> {data?.owner&&<button type="button" className="text-button" onClick={()=>copy(data.owner)}>Copy <Copy size={12}/></button>}<br/>Keeper secret: {data?.keeperConfigured?'Present':'Not configured'} · Last evaluation: {data?new Date(data.lastTick).toLocaleString():'—'}<br/>Run the separate keeper service for unattended cycles. Browser refresh only reads state. A configured secret alone does not mean a keeper is running.</p></section><div className="risk"><ShieldCheck size={18}/>No signing keys in the browser. Live execution requires reviewed protocol adapters and a server-side vault authority.</div><div className="actions"><button className="primary" type="submit" disabled={!data||busy}>Save configuration</button><button className="secondary" type="button" onClick={()=>setDraft(structuredClone(c))}>Discard changes</button></div></form></TabsContent></Tabs>
 <div className="bottom"><span>TEK VAULT / SIMULATION ENVIRONMENT</span><span>Mock prices · {data?'Cycle '+data.cycle:'Connecting'} · {stale?'Keeper idle':'No live execution'}</span></div></main>
 <AlertDialog open={!!confirm} onOpenChange={value=>{if(!value)setConfirm(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Close {confirm?.market||'all open'} positions?</AlertDialogTitle><AlertDialogDescription>This realizes simulated PnL at the next evaluated mock price. The final position close settles the cycle and reserves the configured share of net profit for buyback.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>confirm&&act(confirm)}>Confirm close</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster theme="dark" richColors/></>;
}


