"use client";
import {useEffect,useState,useCallback,useRef} from 'react';
import {Copy,LogIn} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {Connections,MainnetOverview} from './Connections';
import {defaults,MARKETS,type Config,type Event} from '@/lib/engine';

type View={config:Config;owner:string;events:Event[];mode:'mainnet-monitor';keeperConfigured:boolean;authProvider?:'password';storagePersistent?:boolean};
const fields:[keyof Config,string,string][]=[['leverage','Leverage (×)','1–100×; default 5×'],['minRewardUsd','Minimum cycle capital ($)','Minimum capital before opening a cycle'],['takeProfit','Take profit (% ROE)','Before trading costs'],['stopLoss','Stop loss (% ROE)','Positive loss threshold; 1–90%'],['maxPositionUsd','Max position notional ($)','Per market; not collateral'],['slippageBps','Slippage (basis points)','100 bps = 1%'],['cooldownSeconds','Cycle cooldown (seconds)','After the final position closes'],['buybackPercent','Profit to buyback (%)','Share of positive net cycle profit']];
export default function VaultDashboard({view='overview'}:{view?:'overview'|'admin'}){
 const admin=view==='admin';
 const [data,setData]=useState<View|null>(null),[draft,setDraft]=useState<Config>({...defaults,dataSource:'mainnet'}),[error,setError]=useState(''),[auth,setAuth]=useState(false),[busy,setBusy]=useState(false),[failedKey,setFailedKey]=useState<string|null>(null);
 const initialized=useRef(false),pendingConfig=useRef<Config|null>(null);
 const refresh=useCallback(async()=>{try{const response=await fetch(admin?'/api/vault':'/api/public',{cache:'no-store'});const value=await response.json() as View&{error?:string};if(!response.ok){setAuth(response.status===401);throw Error(value.error||'Vault unavailable');}setData(value);setAuth(false);setError('');if(!initialized.current){setDraft({...value.config,dataSource:'mainnet'});initialized.current=true;}}catch(e){setError(e instanceof Error?e.message:'Vault unavailable');}},[admin]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer);},[refresh]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const controller=new AbortController();void Promise.resolve(context.registerTool({name:'read_vault',title:'Read vault status',description:'Read verified mainnet balances, prices and positions. Missing data remains unavailable. Does not trade.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments accepted');const response=await fetch('/api/connections',{cache:'no-store'});if(!response.ok)throw Error('Mainnet data unavailable');return {mode:'mainnet-monitor',snapshot:await response.json()};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
 async function save(retry=false){if(busy)return;const key=retry&&failedKey?failedKey:crypto.randomUUID();const config=retry&&pendingConfig.current?pendingConfig.current:{...draft,dataSource:'mainnet' as const};pendingConfig.current=structuredClone(config);setBusy(true);setFailedKey(null);try{const response=await fetch('/api/vault',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({type:'configure',config})});const result=await response.json() as View&{error?:string};if(!response.ok){if(response.status>=500)setFailedKey(key);throw Error(result.error||'Could not save settings');}setData(result);setDraft({...result.config,dataSource:'mainnet'});toast.success('Configuration saved');}catch(e){if(e instanceof TypeError)setFailedKey(key);toast.error(e instanceof Error?e.message:'Could not save settings');}finally{setBusy(false);}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);toast.success('Copied');}catch{toast.error('Could not copy address');}}
 const config=data?.config||{...defaults,dataSource:'mainnet' as const};
 return <><header className="topbar"><a className="wordmark" href="/">LONG<span> / VAULT</span></a>{admin&&<div className="topnav"><a href="/" className="admin-link">← Back to vault</a></div>}</header>
 <main className={admin?'admin-page':'dashboard'}>
 {admin?<div className="admin-heading">{data?.authProvider==='password'&&<form action="/admin/logout" method="post"><button className="text-button" type="submit">Sign out</button></form>}<span className="eyebrow">VAULT MANAGEMENT</span><h1>Admin</h1><p>Configure the project and verify its mainnet connections.</p></div>:<div className="hero"><div className="token-emblem"><img src="/long-pfp.png" alt="$LONG profile icon" width={1254} height={1254}/></div><h1>$LONG</h1><p>BTC, ETH &amp; SOL. One vault.<br/><span>Creator rewards. Long positions. $LONG buybacks.</span></p><div className="address"><label>VAULT</label><span>{config.vault||'Vault not configured'}</span>{config.vault&&<button aria-label="Copy vault address" onClick={()=>copy(config.vault)}><Copy size={12}/></button>}</div></div>}
 {error&&<div role="alert" className={auth?'signin-note':'error-box'}>{auth?<a className="sign-in" href="/signin-with-chatgpt?return_to=%2Fadmin" target="_top"><LogIn size={14}/> Sign in to Admin</a>:<>{error} <button className="secondary" onClick={()=>refresh()}>Retry</button></>}</div>}
 {!admin&&<MainnetOverview config={config} copy={copy}/>}
 {admin&&<div className="admin-content">
 <section className="panel settings-section"><h2>Execution status</h2><p>Read-only mainnet monitoring. Claims, position management and buybacks are not enabled. Previews below cannot sign or send transactions.</p><div className="actions"><button className="secondary" disabled>Claim rewards</button><button className="secondary" disabled>Open cycle</button><button className="secondary" disabled>Close positions</button><button className="secondary" disabled>Buy back</button></div></section>
 {failedKey&&<div role="alert" className="error-box">Save was not confirmed. <button className="secondary" disabled={busy} onClick={()=>save(true)}>Retry same save</button></div>}
 <form onSubmit={e=>{e.preventDefault();void save();}}><section className="panel settings-section"><h2>Strategy &amp; risk limits</h2><p>Saved strategy settings inform previews. Saving them does not activate trading.</p><div className="field-grid">{fields.map(([key,label,hint])=><label key={key}>{label}<input required type="number" step="any" value={Number.isFinite(draft[key] as number)?draft[key] as number:''} onChange={e=>setDraft({...draft,[key]:e.target.value===''?NaN:Number(e.target.value)})}/><small>{hint}</small></label>)}</div><h2>Capital allocation <small>Total {MARKETS.reduce((n,m)=>n+draft.allocation[m],0)}%</small></h2><div className="field-grid">{MARKETS.map(m=><label key={m}>{m} allocation (%)<input required type="number" min="0" max="100" step="0.1" value={draft.allocation[m]} onChange={e=>setDraft({...draft,allocation:{...draft.allocation,[m]:Number(e.target.value)}})}/></label>)}</div></section>
 <section className="panel settings-section"><h2>Vault &amp; treasury</h2><div className="field-grid">{([['vault','Vault address'],['treasury','Treasury address'],['tokenMint','$LONG token contract'],['creator','Creator wallet (optional verification)']] as const).map(([key,label])=><label key={key}>{label}<input autoComplete="off" spellCheck={false} value={draft[key]||''} placeholder="Solana public address" onChange={e=>setDraft({...draft,[key]:e.target.value.trim()})}/></label>)}</div><p>Save the CA here to update the website. The on-chain creator is discovered from the CA. Public addresses only.</p></section>
 <section className="panel settings-section"><h2>Server connections</h2><div className="field-grid"><label>RPC secret reference<input readOnly value={draft.rpcEnv}/><small>Configure in Railway Variables.</small></label><label>Jupiter API secret reference<input readOnly value={draft.jupiterEnv}/><small>Official Jupiter perpetuals API.</small></label></div>{data?.storagePersistent===false&&<p className="negative">Storage is temporary. Attach a Railway volume and set DATA_DIR=/data.</p>}<p className="admin-note">Admin ID: {data?.owner||'Sign in first'}</p></section>
 <div className="actions"><button type="submit" className="primary" disabled={!data||busy}>{busy?'Saving…':'Save configuration'}</button><button type="button" className="secondary" onClick={()=>setDraft({...config,dataSource:'mainnet'})}>Discard changes</button></div></form>
 <Connections config={config}/>
 <section className="panel settings-section"><h2>Settings history</h2>{data?.events.length?data.events.slice(0,20).map(event=><p key={event.id}>{new Date(event.time).toLocaleString()} · Configuration saved</p>):<p>No configuration changes recorded.</p>}</section>
 </div>}
 <div className="bottom"><span>LONG VAULT</span><span>Mainnet data · Trading not enabled</span></div></main><Toaster theme="dark" richColors/></>;
}
