"use client";
import {useEffect,useState,useCallback,useRef} from 'react';
import {Copy,LayoutDashboard,SlidersHorizontal,Plug,Activity,LogOut,Save} from 'lucide-react';
import {HoloCandle} from './HoloCandle';
import {Toaster,toast} from 'sonner';
import {MainnetOverview} from './Connections';
import {AdminConsole} from './AdminConsole';
import {ConnectionSettings} from './ConnectionSettings';
import {StrategySettings} from './StrategySettings';
import {LiveTrading} from './LiveTrading';
import {defaults,type Config} from '@/lib/engine';
import type {WalletStatus} from '@/lib/dev-wallet';
type View={testMode?:boolean;authProvider?:string;config:Config;developerWallet?:WalletStatus;walletStorageError?:string;storagePersistent?:boolean;trading?:{enabled:boolean;paused:boolean;phase?:string;nextAt?:number}};
export default function VaultDashboard({view='overview'}:{view?:'overview'|'admin'}){
 const admin=view==='admin';
 const [section,setSection]=useState('overview');
 const [liveStatus,setLiveStatus]=useState<{enabled:boolean;paused:boolean}|null>(null);
 const sections=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'strategy',label:'Strategy',icon:SlidersHorizontal},{id:'connections',label:'Connections',icon:Plug},{id:'activity',label:'Activity',icon:Activity}];
 const [data,setData]=useState<View|null>(null),[ca,setCa]=useState(''),[key,setKey]=useState(''),[cycle,setCycle]=useState(120),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const initialized=useRef(false);
 const refresh=useCallback(async()=>{try{const r=await fetch(admin?'/api/vault':'/api/public',{cache:'no-store'});const value=await r.json() as View & {error?:string};if(!r.ok)throw Error(value.error||'Vault unavailable');setData(value);setError('');if(!initialized.current){setCa(value.config.tokenMint);setCycle(value.config.cooldownSeconds);initialized.current=true;}}catch(e){setError(e instanceof Error?e.message:'Vault unavailable');}},[admin]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer);},[refresh]);
 async function copy(value:string){try{await navigator.clipboard.writeText(value);toast.success('Copied');}catch{toast.error('Could not copy address');}}
 async function save(){if(busy)return;setBusy(true);try{const r=await fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tokenMint:ca.trim(),cycleSeconds:cycle,...(key?{privateKey:key.trim()}:{})})});const result=await r.json() as {error?:string};if(!r.ok)throw Error(result.error||'Setup failed');setKey('');await refresh();toast.success('Saved. Cycles are paused until you enable them.');}catch(e){toast.error(e instanceof Error?e.message:'Save could not be confirmed. Check the current wallet before retrying.');}finally{setBusy(false);}}
 const config=data?.config||{...defaults,dataSource:'mainnet' as const};
 return <><header className="topbar"><a className="wordmark" href="/">LONG<span> / VAULT</span></a>{admin&&<a className="admin-link" href="/">← Back to $LONG</a>}</header><main className={admin?'admin-page':'dashboard'}>
 {admin?<div className="admin-heading"><form method="post" action="/admin/logout"><button className="secondary"><LogOut size={14}/> Sign out</button></form><span className="eyebrow">LONG CONTROL</span><h1>Control room<span>.</span></h1><p>Your token, strategy, and execution. All in one place.</p></div>:<section className="hero holo-hero"><div className="holo-copy"><span className="eyebrow">THE $LONG PROTOCOL</span><h1>$LONG<span className="hero-dot">.</span></h1><p>Fees fuel the longs.<br/><span>Profits feed the chart.</span></p><div className="address"><label>TOKEN CA</label><span>{config.tokenMint||'Not configured'}</span>{config.tokenMint&&<button aria-label="Copy token contract address" onClick={()=>copy(config.tokenMint)}><Copy size={14}/></button>}</div></div><HoloCandle/></section>}
 {!admin&&<section className="tek-flow" aria-label="How the automation works"><div><span>01 / COLLECT</span><p>Creator rewards</p></div><b aria-hidden="true">→</b><div><span>02 / DEPLOY</span><p>BTC · ETH · SOL longs</p></div><b aria-hidden="true">→</b><div><span>03 / RETURN</span><p>Realized profit → $LONG</p></div></section>}
 {error&&<p role="alert" className="error-box">{error} {admin&&<a href="/admin/login">Sign in</a>}</p>}
 {!admin&&<MainnetOverview config={config} copy={copy} trading={data?.trading}/>}
 {admin&&<div className="admin-content"><div className="admin-summary"><div><span>Automation</span><strong>{!liveStatus?'Unavailable':!liveStatus.enabled?'Not enabled':liveStatus.paused?'Paused':'Running'}</strong></div><div><span>Leverage</span><strong>{data?config.leverage+'×':'—'}</strong></div><div><span>Profit to buybacks</span><strong>{data?config.buybackPercent+'%':'—'}</strong></div><div><span>Cycle interval</span><strong>{data?config.cooldownSeconds+'s':'—'}</strong></div></div><nav className="admin-tabs" aria-label="Admin sections">{sections.map(({id,label,icon:Icon})=><button type="button" key={id} aria-current={section===id?'page':undefined} onClick={()=>setSection(id)}><Icon size={16}/>{label}</button>)}</nav><div hidden={section!=='overview'}><form onSubmit={e=>{e.preventDefault();void save();}}><section className="panel settings-section"><div className="panel-heading"><span className="section-index">01</span><div><h2>Token & wallet</h2><p>The essentials that power your cycle.</p></div></div><div className="field-grid">
 <label>$LONG token CA{data?.testMode?' (optional in test mode)':''}<input required={!data?.testMode} autoComplete="off" spellCheck={false} value={ca} placeholder="Token contract address" onChange={e=>setCa(e.target.value)}/><small>Updates the public website and identifies the fee creator.</small></label>
 <label>Developer wallet private key<input type="password" disabled={data?.authProvider!=='password'} autoComplete="new-password" spellCheck={false} maxLength={512} value={key} required={!data?.developerWallet?.publicKey} placeholder={data?.developerWallet?.publicKey?'Wallet saved · leave blank to keep':'Base58 key or JSON byte array'} onChange={e=>setKey(e.target.value)}/><small>Encrypted on the server. Never displayed again. This wallet claims the fees and funds the longs.</small></label>
 <label>Cycle interval (seconds)<input required type="number" min={10} max={86400} step={1} value={Number.isFinite(cycle)?cycle:''} onChange={e=>setCycle(e.target.value===''?NaN:Number(e.target.value))}/><small>Wait after a completed cycle before starting the next.</small></label></div>
 {data?.developerWallet?.publicKey&&<p className="admin-note">Developer wallet <code>{data.developerWallet.publicKey}</code></p>}{data?.walletStorageError&&<p role="alert" className="negative">{data.walletStorageError}</p>}{data?.storagePersistent===false&&<p className="negative">Attach a Railway volume and set DATA_DIR=/data to save the wallet.</p>}
 <p className="admin-note">{data&&data.authProvider!=='password'?'Local preview only. Save your wallet on the deployed Admin page.':''}</p><div className="actions"><button className="primary" disabled={busy||!data||data.authProvider!=='password'}><Save size={15}/>{busy?'Saving…':'Save setup'}</button></div><p className="admin-note">Current strategy: {config.leverage}× longs · BTC {config.allocation.BTC}% / ETH {config.allocation.ETH}% / SOL {config.allocation.SOL}% · TP +{config.takeProfit}% / SL −{config.stopLoss}% ROE · ${config.maxPositionUsd} maximum per position.</p></section></form><LiveTrading onStatus={setLiveStatus}/></div><div hidden={section!=='strategy'}>{data&&<StrategySettings config={config} enabled={data.authProvider==='password'} onSaved={refresh}/>}</div><div hidden={section!=='connections'}>{data&&<ConnectionSettings enabled={data.authProvider==='password'}/>}</div><div hidden={section!=='activity'}>{data&&<AdminConsole enabled={data.authProvider==='password'}/>}</div></div>}
 <div className="bottom"><span>LONG</span><span>Solana mainnet</span></div></main><Toaster theme="dark" richColors/></>;
}
